In [8]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import numpy as np

In [5]:
model = LinearRegression(normalize=True)
model

LinearRegression(normalize=True)

In [9]:
X,y = np.arange(10).reshape((5,2)),range(5)

In [10]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
list(y)

[0, 1, 2, 3, 4]

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [21]:
X_train

array([[4, 5],
       [0, 1],
       [2, 3]])

In [22]:
model.fit(X_train,y_train)

LinearRegression(normalize=True)

In [23]:
model.predict(X_test)

array([3., 4.])

In [24]:
X_test

array([[6, 7],
       [8, 9]])

In [29]:
model.score(X_test,y_test)

1.0