#### Numpy
- is a linear algebra library for Python
- almost all of the libraries in the PyData ecosystem rely on NumPy as one of their main building blocks
- incredibly fast, as it has bindings to C libraries

Numpy arrays come in two flavors:
1. Vectors
- strictly 1D arrays
2. Matrices
- 2D
- But a matrix can still have only one row or one column

In [1]:
import numpy as np

In [4]:
# Vector
np.array([1,2,3])

array([1, 2, 3])

In [5]:
# Matrix
np.array([[1,2,3], [4,5,6], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# Similar to Python range() function
np.arange(0,10,2) # (start, end, step_size)

array([0, 2, 4, 6, 8])

In [9]:
# Create array of zeros
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5)) # (num_rows, num_cols)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
# Create array of 1s
np.ones(4)

array([1., 1., 1., 1.])

In [14]:
# Create array of evenly spaced numbers
np.linspace(0,5,10) # (start, end, how many)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
# Create an identity matrix - num_rows == num_cols - 1s in main diagonal
np.eye(4) # num_rows

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
# Generate uniform-distributed random numbers from 0 to 1
np.random.rand(4)

array([0.72529107, 0.02839997, 0.08539843, 0.9803267 ])

In [20]:
np.random.rand(4,3) #shape

array([[0.89566816, 0.88415946, 0.74321407],
       [0.02555933, 0.93630823, 0.87224874],
       [0.48787726, 0.14715843, 0.44818549],
       [0.70599612, 0.95153597, 0.05230493]])

In [21]:
# Generate standard normal distribution centered around 0 random numbers
np.random.randn(2) #shape

array([1.36540668, 1.2754967 ])

In [23]:
np.random.randint(1,100,10) # (start, end, shape)

array([47, 14, 55,  1, 49, 65, 53, 28, 30,  8])

In [31]:
arr = np.arange(25)
randarr = np.random.randint(1,50,10)

In [34]:
randarr

array([49,  5,  3, 45, 11, 16,  2, 28, 14, 26])

In [26]:
# Reshape
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
# Find max value
randarr.max()

49

In [33]:
# Find min value
randarr.min()

2

In [36]:
# Index location of m
randarr.argmax()

0

In [37]:
randarr.argmin()


6

In [38]:
# Indicates that this is a vector -> (n,)
arr.shape

(25,)